/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ArticleInput = IDL.Record({
  'title' : IDL.Text,
  'publishDate' : Time,
  'body' : IDL.Text,
  'slug' : IDL.Text,
  'coverImage' : ExternalBlob,
  'category' : IDL.Text,
  'subtitle' : IDL.Opt(IDL.Text),
});
export const Article = IDL.Record({
  'title' : IDL.Text,
  'publishDate' : Time,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'slug' : IDL.Text,
  'coverImage' : ExternalBlob,
  'category' : IDL.Text,
  'subtitle' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ArticleSummary = IDL.Record({
  'title' : IDL.Text,
  'publishDate' : Time,
  'slug' : IDL.Text,
  'coverImage' : ExternalBlob,
  'category' : IDL.Text,
  'subtitle' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkArticleExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createArticle' : IDL.Func([ArticleInput], [], []),
  'deleteArticle' : IDL.Func([IDL.Text], [], []),
  'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPendingArticles' : IDL.Func([], [IDL.Vec(ArticleSummary)], ['query']),
  'getPublishedArticles' : IDL.Func([], [IDL.Vec(ArticleSummary)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateArticle' : IDL.Func([IDL.Text, ArticleInput, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ArticleInput = IDL.Record({
    'title' : IDL.Text,
    'publishDate' : Time,
    'body' : IDL.Text,
    'slug' : IDL.Text,
    'coverImage' : ExternalBlob,
    'category' : IDL.Text,
    'subtitle' : IDL.Opt(IDL.Text),
  });
  const Article = IDL.Record({
    'title' : IDL.Text,
    'publishDate' : Time,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'slug' : IDL.Text,
    'coverImage' : ExternalBlob,
    'category' : IDL.Text,
    'subtitle' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ArticleSummary = IDL.Record({
    'title' : IDL.Text,
    'publishDate' : Time,
    'slug' : IDL.Text,
    'coverImage' : ExternalBlob,
    'category' : IDL.Text,
    'subtitle' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkArticleExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createArticle' : IDL.Func([ArticleInput], [], []),
    'deleteArticle' : IDL.Func([IDL.Text], [], []),
    'getArticleBySlug' : IDL.Func([IDL.Text], [IDL.Opt(Article)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPendingArticles' : IDL.Func([], [IDL.Vec(ArticleSummary)], ['query']),
    'getPublishedArticles' : IDL.Func([], [IDL.Vec(ArticleSummary)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateArticle' : IDL.Func([IDL.Text, ArticleInput, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };